// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoBPpZfRnYihY306gjEBzFswHS2TsPV0s',
    appId: '1:128458254874:web:63e55d9e1a40b085d47fa3',
    messagingSenderId: '128458254874',
    projectId: 'mapbox-firebase-f73ad',
    authDomain: 'mapbox-firebase-f73ad.firebaseapp.com',
    storageBucket: 'mapbox-firebase-f73ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnLP6YFAhXSn-PZlSn2LWSy4Y8VEfIS_U',
    appId: '1:128458254874:android:9964a1573b07803cd47fa3',
    messagingSenderId: '128458254874',
    projectId: 'mapbox-firebase-f73ad',
    storageBucket: 'mapbox-firebase-f73ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRABYpf4Fiwd4mjgZSQm5d93btjKmpIFk',
    appId: '1:128458254874:ios:29d92de2b3c1c7e3d47fa3',
    messagingSenderId: '128458254874',
    projectId: 'mapbox-firebase-f73ad',
    storageBucket: 'mapbox-firebase-f73ad.appspot.com',
    iosBundleId: 'com.example.mapboxFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRABYpf4Fiwd4mjgZSQm5d93btjKmpIFk',
    appId: '1:128458254874:ios:29d92de2b3c1c7e3d47fa3',
    messagingSenderId: '128458254874',
    projectId: 'mapbox-firebase-f73ad',
    storageBucket: 'mapbox-firebase-f73ad.appspot.com',
    iosBundleId: 'com.example.mapboxFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoBPpZfRnYihY306gjEBzFswHS2TsPV0s',
    appId: '1:128458254874:web:bb773fd06c8e5a91d47fa3',
    messagingSenderId: '128458254874',
    projectId: 'mapbox-firebase-f73ad',
    authDomain: 'mapbox-firebase-f73ad.firebaseapp.com',
    storageBucket: 'mapbox-firebase-f73ad.appspot.com',
  );
}
